### ISSUE TITLE
Can Jetson Xavier real-time too?

### ISSUE THREAD

**Issue by littleggghost** [kozyilmaz/nvidia-jetson-rt#1]
Hi, @kozyilmaz 
    I use this similar way to configure the Ubuntu18.04 4.9 kernel on the newest Xavier,  but fails occured while compiling it. The packages I use is the newest Jetpack 4.1.
Do you have any advise?

**Comment by littleggghost** [comment]
@kozyilmaz 
I recently seen a method, which must download the patchs first:
"cd kernel-4.9
./scripts/rt-patch.sh apply-patches"
Can this work?

**Comment by kozyilmaz** [comment]
Hi @littleggghost, I am not sure about the recent developments (or boards). If you have a log for compilation issues I may take a look.

**Comment by littleggghost** [comment]
Hi again, @kozyilmaz 
I find the reason,  the tool chain should change to GCC 6.4.1, not 4.8.5.
After reboot, under this folder "/lib/modules", I can find "4.9.108-rt76-rt" and "4.9.108-tegra",  and it shows the tegra kernel when I run "uname -a".
But I can't run the rt kernel, because I can't choose to use which kernel. The TX2 runs the new rt kernel automatically, but it seems not on Xavier.
Have you ever met this similar situation?

**Comment by littleggghost** [comment]
I try to delete the "4.9.108-tegra" folder, but it does't work. It shows nothing now when I run "lsmod".

**Comment by kozyilmaz** [comment]
@littleggghost I do not own a Xavier board so I am not exactly sure whats happening. Did you update the images on the board after compilation?
https://github.com/kozyilmaz/nvidia-jetson-rt/blob/master/docs/README.03-realtime.md#copy-binaries-to-l4t-for-deployment
https://github.com/kozyilmaz/nvidia-jetson-rt/blob/master/docs/README.03-realtime.md#target-update-kernel-and-drivers-on-jetson-board

**Comment by littleggghost** [comment]
Yes, I use the new Image file generated. 
I guess that the Image file works on TX2, but not on Xavier, maybe somewhere changes.
It always load the normal kernel.

**Comment by littleggghost** [comment]
I also try the zImage file, it doesn't work too.
